import { h, list, p, type Post } from '../types'

export const post: Post = {
  slug: 'jiu-jitsu-etiquette',
  title: 'Jiu-Jitsu Etiquette & Beginner Survival Guide',
  date: '2025-11-28',
  category: 'guide',
  excerpt: 'Walking into your first Brazilian Jiu-Jitsu class can feel intimidating.',
  cover: {
    src: '/site/blog/jiu-jitsu-etiquette.webp',
    alt: 'The slap and fist bump that starts every round',
    w: 720,
    h: 500,
  },
  body: [
    p('Walking into your first Brazilian Jiu-Jitsu class can feel intimidating. Everyone has been there. The good news? You don’t need to be in shape, flexible, or experienced. You just need the right mindset and a few simple guidelines.'),
    p('This is the official Fight Factory beginner guide so you can walk in confident, relaxed, and ready to have fun.'),
    h('1. Show Up 10–15 Minutes Early'),
    p('This gives you time to:'),
    list([
      'Meet the instructor',
      'Fill out any forms',
      'Get shown around',
      'Ask beginner questions',
    ]),
    p('Being early removes 90% of the new-gym anxiety.'),
    h('2. Wear Comfortable Training Clothes'),
    p('If you don’t have a gi yet, that’s totally fine.'),
    p('Wear:'),
    list([
      'T-shirt or rashguard',
      'Shorts or leggings',
      'Flip-flops',
    ]),
    p('You can always borrow a gi or buy one later.'),
    h('3. Respect the Mat'),
    p('This is the #1 rule in every BJJ academy.'),
    list([
      'No shoes on the mat',
      'Wear flip-flops when stepping off',
      'Keep fingernails and toenails trimmed',
      'Keep gear clean',
    ]),
    p('Hygiene keeps everyone safe.'),
    h('4. Pay Attention During Technique'),
    p('You’re not expected to master anything.'),
    p('You are expected to:'),
    list([
      'Watch',
      'Listen',
      'Try your best',
      'Ask questions',
    ]),
    p('Nobody expects perfection, only effort.'),
    h('5. Tap Early, Tap Often'),
    p('This is how we train safely.'),
    p('If something feels:'),
    list([
      'Tight',
      'Uncomfortable',
      'Stuck',
      'Confusing',
    ]),
    p('Just tap. Your partner stops instantly.'),
    h('6. Leave the Ego at the Door'),
    p('You won’t be the strongest, fastest, or best person in the room. Not yet.'),
    p('But if you’re humble and consistent, you’ll improve faster than 90% of beginners.'),
    h('7. Expect to Get Tired (In a Good Way)'),
    p('BJJ uses muscles you never use in normal life.'),
    p('It’s totally normal to feel:'),
    list([
      'Out of breath',
      'Sore',
      'Overwhelmed',
    ]),
    p('Give it 3–5 classes, it clicks quickly.'),
    h('Ready to Try Your First Class?'),
    p('If you’re in Austin, come try a FREE trial week at Fight Factory Jiu-Jitsu.'),
    p('Beginner-friendly. Zero pressure. We’ll guide you through everything.'),
    p('👉 Click here to book your free trial.'),
  ],
}
