import { h, list, p, type Post } from '../types'

export const post: Post = {
  slug: 'gi-vs-no-gi',
  title: 'Gi vs No-Gi: What’s the Difference and Which Should You Start With?',
  date: '2025-11-28',
  category: 'guide',
  excerpt: 'Both are BJJ. Both build skills. Both make you better.',
  cover: {
    src: '/site/programs/adults-gi.webp',
    alt: 'An adults gi class training on the main mat',
    w: 1324,
    h: 1000,
  },
  body: [
    p('If you’re new to Brazilian Jiu-Jitsu, one of the first questions is:'),
    p('“Should I train gi or no-gi first?”'),
    p('Both are BJJ. Both build skills. Both make you better.'),
    p('But they have different benefits, and knowing the difference will help you start the right way.'),
    h('What Is Gi Jiu-Jitsu?'),
    p('Gi BJJ uses the traditional kimono (jacket, pants, belt).'),
    p('You can grab the sleeves, collar, and pants to control your partner.'),
    h('Benefits of Gi'),
    list([
      'Slower, more technical learning',
      'Stronger fundamentals',
      'More grips = more control',
      'Great for self-defense',
      'Helps smaller people neutralize bigger ones',
    ]),
    h('What Is No-Gi Jiu-Jitsu?'),
    p('No-gi uses:'),
    list([
      'Rashguard',
      'Shorts',
      'Compression gear',
    ]),
    p('It’s faster and more slippery because there are no grips.'),
    h('Benefits of No-Gi'),
    list([
      'Faster pace, great cardio',
      'Better for MMA crossover',
      'Powerful wrestling influence',
      'Great for scrambles and athletic movement',
    ]),
    h('Which One Should You Start With?'),
    p('Short answer:'),
    h('👉'),
    h('Start with the class that fits your schedule.'),
    p('The MOST important thing is consistency.'),
    p('But if you want a recommendation:'),
    h('If you’re a total beginner'),
    p('Start with Gi, you’ll learn mechanics and control faster.'),
    h('If your main interest is MMA'),
    p('Start with No-Gi, it matches cage movement better.'),
    h('If your goal is fitness'),
    p('Both work perfectly.'),
    h('Why Training Both Makes You Better'),
    p('Well-rounded BJJ practitioners train both because:'),
    list([
      'Gi builds strong fundamentals.',
      'No-gi builds speed and reactions.',
      'Both improve your grappling IQ.',
    ]),
    p('At Fight Factory, we recommend mixing both within your first 3–6 months.'),
    h('Want to Try Gi and No-Gi in Austin?'),
    p('Fight Factory Jiu-Jitsu offers:'),
    list([
      'Daily gi classes',
      'Daily no-gi classes',
      'Beginner-friendly coaching',
      'A free trial week for new students',
    ]),
    p('👉 Start your free trial today.'),
  ],
}
